# Generated by Django 5.2.12 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_seed_default_tiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontier",
            name="paypal_plan_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="paypal_subscription_id",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
