export const USER_SIGNIN = "USER_SIGNIN";
export const USER_SIGNOUT = "USER_SIGNOUT";
export const USER_REGISTER = "USER_REGISTER";
export const USER_APPLY_SELLER = "USER_APPLY_SELLER";
export const USER_LIST_UPDATE = "USER_LIST_UPDATE";
